config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end

  root 'forum_threads#index'
  get 'pages/home'

end

app/models/forum_post.rb
class ForumPost < ActiveRecord::Base
  belongs_to :forum_thread
  belongs_to :user

  validates :body, presence: true
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
  belongs_to :user
  has_many :forum_posts
  has_many :users, through: :forum_posts

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
  validates_associated :forum_posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, :uniqueness => { :case_sensitive => false }

  has_many :forum_threads
  has_many :forum_posts

  # This will allow us to login with username or password
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  # Override find_for_database_authentication
  # If you're not using PostgreSQL you may run into some problems here
  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions.to_hash).first
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }  
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThreads::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new(forum_post_params)
    @forum_post.user = current_user

    if @forum_post.save
      redirect_to forum_thread_path(@forum_thread), notice: "Your post was added! Great job!"
    else
      redirect_to @forum_thread, alert: "Unable to save your post!"
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]

  def index
    @forum_threads = ForumThread.order("created_at DESC")
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.new
  end

  def create
    #@forum_thread = ForumThread.new(forum_thread_params)
    @forum_thread = current_user.forum_threads.build(forum_thread_params)
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread, notice: "Your post was saved!"
    else
      render 'new'
    end
  end

  def show
    @forum_post = ForumPost.new
  end

  private
    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/forum_posts/_form.html.erb
<%= form_for [@forum_thread, @forum_post] do |f| %>
  <%= f.text_area :body, placeholder: "Add your comment!", rows: "10" %>
  <br>
  <%= f.submit %>
<% end %>

app/views/forum_posts/_forum_post.html.erb
<%= div_for forum_post do %>
  <p class="author">Posted by <%= forum_post.user.username %> on <%= forum_post.created_at %></p>
  <p><%= forum_post.body %></p>
<% end %>

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <%= f.text_field :subject, placeholder: "Subject" %>
  <br><br>
  <%= f.fields_for :forum_posts do |p| %>
    <%= p.text_area :body, placeholder: "Your Message", rows: "10" %>
  <% end %>

  <br><br>
  <%= f.submit %>
<% end %>

app/views/forum_threads/index.html.erb
<div id="forum_thread_index">
  <%= link_to "New Post", new_forum_thread_path, class: "button" %> <br>
<% @forum_threads.each do |forum_thread| %>
  <div class="thread">
    <h2 class="title"><%= link_to forum_thread.subject, forum_thread_path(forum_thread) %></h2>
    <p class="date">Published <%= time_ago_in_words(forum_thread.created_at) %> ago  by <%= forum_thread.user.username %>.
      There are <%= forum_thread.forum_posts.count %> posts under it.</p>
  </div>
<% end %>

<% if @forum_threads.empty?  %>
  <div class="thread">
    <h2 class="title">It looks like there are no posts!</h2>
    <p class="date">You can start one <%= link_to "here", new_forum_thread_path %></p>
  </div>
<% end %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>
<%= render 'form' %>

app/views/forum_threads/show.html.erb
<%= @forum_thread.subject %>
<br>
<%= @forum_thread.user.username %>
<hr/>
<%= render @forum_thread.forum_posts %>
<hr />
<%= render partial: "forum_posts/form" %>

app/views/layouts/_header.html.erb
<div class="main_header">
  <div class="container clearfix">
      <div id="brand">
        <%= link_to "SimpleForum", root_path %>
      </div>

      <div id="nav">
        <% if user_signed_in? %>
          Welcome <%= current_user.username %>
          <%= link_to "View Threads", forum_threads_path, class: "primary" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleForum</title>
  <link href="//fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet" type"text/css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |key, value| %>
    <div id="notice_wrapper">
      <div class="<%= key %>">
        <i class="fa fa-times-circle fa-4 alert_close"></i>
        <%= value %>
      </div>
    </div>
  <% end %>
  
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>